#if defined(STM32F1)
#define HAL_ADC_MODULE_DISABLED
#define HAL_CRC_MODULE_DISABLED
#define HAL_I2C_MODULE_DISABLED
#define HAL_I2S_MODULE_DISABLED
#define HAL_SPI_MODULE_DISABLED
#define HAL_RTC_MODULE_DISABLED
#define HAL_SAI_MODULE_DISABLED
#define HAL_ICACHE_MODULE_DISABLED
#define HAL_SUBGHZ_MODULE_DISABLED
#define HAL_TIM_MODULE_ENABLED
#endif
//#if defined(STM32F0)
//#define HAL_ADC_MODULE_DISABLED
//#define HAL_I2C_MODULE_DISABLED
//#define HAL_SPI_MODULE_DISABLED
//#define HAL_RTC_MODULE_DISABLED
//#define HAL_TIM_MODULE_ENABLED
//#endif